### ISSUE TITLE
插件会自动给数学公式加上 \，

### ISSUE THREAD

**Issue by yifan0414** [tonngw/acwing-helper#1]
<img width="942" alt="image" src="https://github.com/tonngw/acwing-helper/assets/45898625/26266318-47ac-4c34-90cb-f3c02dc53396">

<img width="665" alt="image" src="https://github.com/tonngw/acwing-helper/assets/45898625/335e3ee9-98d3-4ec8-b044-3ab83958f60a">

**Comment by yifan0414** [comment]
多了一个 \

**Comment by tonngw** [comment]
麻烦提供一下原题链接

**Comment by yifan0414** [comment]
只要带有数学公式的题目都有这个问题，比如 https://www.acwing.com/problem/content/267/

**Comment by tonngw** [comment]
ok, 晚点回复你，现在在外面

**Comment by tonngw** [comment]
在 AcWing 的题解页面是没有问题的，但在本地的 Markdown 编辑器中确实存在这样的问题。
解决方案：替换脚本代码中最后的 handleHtml 函数，可以解决你的问题，在使用中遇到问题可以继续在这个 issue 中反馈对应的题目链接，我会在下个版本中修复这个问题。
```js
function handleHtml(html) {
    // 处理数学公式
    turndownService.addRule("strikethrough", {
	    filter: ["script"],
	    replacement: function (content) {
		    content = content.replace(/\\\\/g, "\\"); 
		    content = content.replace(/\\_/g, "_");
		    content = content.replace(/\\\[/g, "[");
		    content = content.replace(/\\\]/g, "]");
		    content = content.replace(/\\-/g, "-");
		    return "$" + content + "$";
	    },
    });
    
    // 跳过 span 标签，不进行处理
    turndownService.remove("span");
    var markdown = turndownService.turndown(html);
    return markdown;
}
```

**Comment by yifan0414** [comment]
谢谢

**Comment by tonngw** [comment]
> 谢谢

你测试了吗，应该可以正常使用了。
