### ISSUE TITLE
大佬，acwing left 布局的时候，可以把题目名字做一个坍缩嘛

### ISSUE THREAD

**Issue by funcdfs** [tonngw/acwing-helper#2]
![image](https://github.com/tonngw/acwing-helper/assets/56250171/b47760be-9f8f-4472-8a70-d8d3b4d4fddf)

这是 leetcode 周赛的时候，可以切换布局达到的效果。也符合 leetcode 模式下的刷题习惯，空间利用率很高。

语言描述可能不太清晰，我截了个图，  如下   
紫色区域可以完全删除，然后题目标题挪到绿色框（左对齐）然后其他提交记录等挪到绿色框（右对齐）

![image](https://github.com/tonngw/acwing-helper/assets/56250171/0e0971f5-b99b-432e-a99d-611221f4b148)

试着改了改，由于前端功底不扎实，实在有心无力不好实现，望大佬考虑这个建议！

**Comment by tonngw** [comment]
感谢你的建议，我理解了你的想法并试着简单修改了一下，其实我也想完善这个布局，但这个结果并不是我最终想要的，我想做成第一张图那样，不过好的产品确实需要花费一些精力和时间打磨，欢迎 PR。
![image](https://github.com/tonngw/acwing-helper/assets/33111688/1cc08473-f04d-4c3f-b0a5-20fbd7d06ef6)
